### ISSUE TITLE
log feature causes out of memory exception on the client side

### ISSUE THREAD

**Issue by rbattenfeld** [arquillian/arquillian-cube#106]
The new log feature causes an out of memory exception on the client side. My log file was relatively small. Just 300 kBytes.

**Comment by aslakknutsen** [comment]
Related to reading log into a string here:
https://github.com/arquillian/arquillian-cube/blob/master/docker/src/main/java/org/arquillian/cube/impl/docker/DockerClientExecutor.java#L550

**Comment by rbattenfeld** [comment]
Maby this is important. I recognized that attaching jvisualvm to the surfire java instance and analyzing the heap memory, at the end of the test the heap memory consumption rises over 3 GB memory. That means, even I set more memory say 2GB, it was still not enough. The file itself was about 300kB. The test included several arquillian test cases. I am not sure if that is also helpful.

Once the stream approach is implemented, I can quickly test this in your lap.

**Comment by lordofthejars** [comment]
Mmmm strange maybe it is related with two issues the first one is the log
itself that is not written directly and the second one that docker-Java
does not release connections. Let s see after fixing these issues how us
doing the memory.
Thank you so much for your work because it is really helpful
El dj., 12 de febr., 2015 a les 19.55 rbattenfeld <notifications@github.com>
va escriure:
