### ISSUE TITLE
Autodownload Docker Machine

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#191]
It might be interesting that if some kind of flag like `checkDockerExistance` is true, the Arquillian Cube checks if `docker` CLI is on PATH, if not then Cube downloads latest Docker Machine, install it, creates a docker machine with the name specified in `machineName` property and then executes the test.

Probably using Arquillian Spacelift is the best way to achieve this since it has support for caching.

**Comment by eddumelendez** [comment]
Currently working on this and AFAIK the only way to get the last version from github is through the GitHub API using the command below and extracting property *name*

```
curl -s https://api.github.com/repos/docker/machine/releases/latest
```

It is valid for the implementation? are there another way to do that? I thought we could do this:
https://github.com/docker/machine/releases/download/latest/docker-machine_darwin-amd64 instead of https://github.com/docker/machine/releases/download/v0.5.6/docker-machine_darwin-amd64 but didn't work.

**Comment by aslakknutsen** [comment]
Maybe this is the time to start using Arquillian Space lift to deal with the different os's etc; https://github.com/arquillian/arquillian-spacelift

**Comment by eddumelendez** [comment]
Yes currently using it to download, give permissions and run docker-machine :)

**Comment by aslakknutsen** [comment]
Ah, sorry. Had forgotten @lordofthejars original comment.. :)

**Comment by eddumelendez** [comment]
You can see my draft here https://github.com/eddumelendez/arquillian-cube/commit/1df78a0281268b70f4bb9871d2dd7c22dd1f38c6

I will wait the feedback before to submit the PR

**Comment by aslakknutsen** [comment]
@eddumelendez You can just send a pull request. The purpose of a pull request is to give feedback..  It's not set in stone. :)

**Comment by eddumelendez** [comment]
@aslakknutsen yes, just wanted to validate the draft before to send the PR. The next review will be over the PR.

**Comment by smiklosovic** [comment]
@eddumelendez very cool feature, +100 for using Spacelift for that.

**Comment by eddumelendez** [comment]
should this ticket be closed?

**Comment by lordofthejars** [comment]
I think so, thanks :)
