### ISSUE TITLE
Is there any Spring Boot containerless test case available?

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-cube#252]
I am looking for the example of Spring Boot with containerless approach. I am struggling to wrap my head around what should be in the Deployment method. I would be _really_ glad to see this in action. Simple POC is enough!

**Comment by lordofthejars** [comment]
well there is a PoC with Undertow, which is the same (or should be) since it is a Main CLI class.
* https://github.com/arquillian/arquillian-cube/blob/master/containerless/src/test/java/org/arquillian/cube/impl/containerless/DaytimeServer.java
* https://github.com/arquillian/arquillian-cube/blob/master/containerless/src/test/java/org/arquillian/cube/impl/containerless/DaytimeTest.java

**Comment by lordofthejars** [comment]
Can I close this issue?
