### ISSUE TITLE
Detect and report error on SS command missing from image when using PollingAwaitStrategy

### ISSUE THREAD

**Issue by aslakknutsen** [arquillian/arquillian-cube#280]
Currently, if the SS command is missing the Cube will just report 'Can not connect to X'. Why it can't connect is not so obvious. 

The call is initiated from here;
https://github.com/jboss-dockerfiles/base/commit/328f451604a917a9680516ab55297811836ee296

The resut of missing command can be seen here;
https://github.com/arquillian/arquillian-cube/blob/master/docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/Ping.java#L54

```
sh: ss: command not found
0
```

Some where this needs to be detected and a UnsupportedOperationException(?) should be thrown.

**Comment by aslakknutsen** [comment]
The ping method in question seems only to be used by the PollinAwaitStrategy when sscommand type is selected. Not sure if we need to introduce some type of 'ValidateRequest' callback so the caller can determine if the result is ok, or attempt to match in general the 'command' attempted to be executed against the Result, or just hardcode it in there.

**Comment by lordofthejars** [comment]
Maybe a log with fatal level?

**Comment by aslakknutsen** [comment]
I think it should fail. Just a log line is to easy to miss.

You have configured something we can't do.

**Comment by adriano-fonseca** [comment]
I am trying put arquilian-cube to run integration tests against wildfly 9 running in a container, follow your github project arquillian-example-cube-helloworld @aslakknutsen, and I got the same error when running the arquilian container wildfly-docker-image. Did you resolve that? I am using arquillian 1.1.8.Final and 1.0.0.Alpha15. Any help would be welcome. The project on github is https://github.com/adriano-fonseca/PlayWithJEE. Thank you.

**Comment by lordofthejars** [comment]
The problem is that the image does not contains `ss` command installed. What you need to do is change the polling strategy to another one (for example `waitforit` http://arquillian.org/arquillian-cube/#_await) or create your own Docker image with `ss` comand installed. Notice that in Alpha16, not released yet, in case of not having `ss` command installed it will fallback automatically to waitforit (https://github.com/arquillian/arquillian-cube/issues/499) What I would suggest is that

1) tries `waitforit` type and see if it works for you (notice that in some cases might not work #499 
2) if waitforit does not work then use type `ping`
3) if not working use the `log` one http://arquillian.org/arquillian-cube/#_await

Next week we are going to release Alpha16, so anotheroption is wait until Alpha16 is released and everything will work in wildfly official image again.

**Comment by adriano-fonseca** [comment]
@lordofthejars I follow your advice and created my own jboss image with iproute(which provides the ss command) and then the arquilian ran the tests. However, even the container have started (and I know that because I can see the wildfly welcome page on the host port that I bind on arquilian.xml) I got the follow error for each one of my tests:

Caused by: java.lang.IllegalStateException: Error launching request at http://localhost:8082/c7ac05fb-5e82-4998-91aa-a6f69e9cebc6/ArquillianServletRunner?outputMode=serializedObject&className=com.company.app.test.EjbTest&methodName=shouldFailStudentNotRemoved. No result returned

Any ideas?
