### ISSUE TITLE
Repository incosistency

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/arquillian-cube#439]
It seems that we have lost commits for Alpha14 release. The tag is around, but the commit is not on master.

Shall we rewrite the history?

Also why do we have two Alpha13 mvn release commits?

**Comment by lordofthejars** [comment]
Strange, I will check on Monday, but probably the problem is how I named
locally repos

**Comment by bartoszmajsak** [comment]
I guess you just forgot to push the master branch, only the tag went through. Which is still fine, but a bit confusing :)

**Comment by lordofthejars** [comment]
Totally agree, sorry for that. I will rename upstream to origin and
viceversa to avoid this happens again

El 24 ago. 2016 11:25 a. m., "Bartosz Majsak" <notifications@github.com>
escribió:

I guess you just forgot to push the master branch, only the tag went
through. Which is still fine, but a bit confusing :)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/arquillian/arquillian-cube/issues/439#issuecomment-242006174>,
or mute the thread

**Comment by jwendell** [comment]
Also, it seems the dev version has changed from 1.0.0.Final-SNAPSHOT to 1.0.0-SNAPSHOT.
(See https://github.com/arquillian/arquillian-cube/commit/6bdb6601259406ec722c18c0e51ca443dd25b7e3 and https://github.com/arquillian/arquillian-cube/commit/57d119889069dbe33221e4f08a980506365e0c52)

Is this an issue per si? Or should I just upgrade my pom to rely on this new version schema? (yes, I use SNAPSHOT version :))

**Comment by lordofthejars** [comment]
This is an error as well, let me fix everything on Monday.

Thanks.

**Comment by bartoszmajsak** [comment]
Seems like a busy Monday :) Let me know if I can support you somehow.
