### ISSUE TITLE
Execute Test On Remote Docker Host ConnectException: Connection timed out: connect

### ISSUE THREAD

**Issue by dimitrichkhartishvili** [arquillian/arquillian-cube#52]
My remote docker host installed on centos 7 in hyper-v vm. configured like in arquillian cube git documentation.
-H tcp://{hostIp}:2375 -H unix:///var/run/docker.sock (for remote connections)
firewalld disabled.
telnet works from windows hostIp:2375
started docker container ports exposed (8080,9990) works to.
everything works.

running tests from windows machine tests not executed.
Exception

.net.ConnectException: Connection timed out: connect
javax.ws.rs.ProcessingException
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

after some research I found arquillian executes tests again  
         http://172.17.42.1:8080/7c832426-9615-4e47-bf74-458813015fa2

ip 172.17.42.1 is internal docker ip which is not visible from LAN.

but correct url must be

     http://{hostIp}:8080/7c832426-9615-4e47-bf74-458813015fa2

**Comment by rbattenfeld** [comment]
Ok, I am not sure now:-) #64 is closed but gives for this here some ideas... But to make progress, what is now open needs to be discussed?

**Comment by lordofthejars** [comment]
Well we need to implement a call to ss inside container with a while to
know when port is ready to receive incoming messages
El ds., 24 de gen., 2015 a les 17.35 rbattenfeld <notifications@github.com>
va escriure:

**Comment by rbattenfeld** [comment]
Hi Alex, Aslak
I worked on this over the last couple of days. I worked mainly of wildfly execution over published ports. Today, I think I made also Tomcat executable. Here is the problem of the jmx stuff. But I think it works now; a new property solves this, I believe. 

Here is the link the the repo: https://github.com/rbattenfeld/arquillian-cube/tree/dynamic-ports

I prepared the profiles in the ftest module:
- wildfly_dynamic_ports
- tomcat_dynamic_ports

You can see that the configuration is slightely different. For example wildfly_dynamic_ports:

wildfly_dynamic_ports:
              image: jboss/wildfly-admin
              exposedPorts: [8080/tcp, 9990/tcp]
              await:
                strategy: sleeping
                sleepTime: 3s
              containerVisible: false
              publishAllPorts: true

Instead of the PortBindings, the publishAllPorts flag instructs docker to assign all exposed ports to an free port of the host. containerVisible is a cube configuration that indicates the the remote container ip address is not visible. I also used here the new sleep wait strategy. WIldfly and Tomcat needs this...

Next, in the remote arquillian container configuration. the host name has to set to the docker host, the ports must be defined but will be later remaped to the published ports.

Finally, what does work and what not. It should work for images which are already pulled down. So, for example image: tutum/tomcat:7.0 works for me but when DockerFile comes in the game then it doesn't work. I asume, this is related to the changed lifecycle  management of the starting the docker container. It is bounded now to BeforeSetup. I made this change because we need the docker ports after the container is started and before the test is kicked on. May you have a better idea.

And, there are some hacks which can be made better. But it should be ok for a POC.

Please let me know if there is something not working as I have described...

**Comment by lordofthejars** [comment]
Ok I have the command for `ss` which looks like `ss -lntu | grep '8080' | grep LISTEN -c`. Now let's implement the await strategy with this.

**Comment by lordofthejars** [comment]
I have just implemented using ss command. Now we only need to update the docker-java client and we are in.
