### ISSUE TITLE
test case using a container object and @CubeIp annotated field in multiple methods fails to set the value of the field 

### ISSUE THREAD

**Issue by rivasdiaz** [arquillian/arquillian-cube#610]
##### Issue Overview

If a test uses the same container object in multiple test methods and uses ```@CubeIp``` annotation (either inside the container object or on the test class), then only the first method call will have the cube ip set.

##### Expected Behaviour

fields annotated with ```@CubeIp``` should have the internal cube address injected before each test method is executed

##### Current Behaviour

Only the first method will see the expected behavior. All other test methods will be executed with the ```@CubeIp``` annotated fields set to null.

##### Steps To Reproduce
1. create a test case with a container object and a field annotated with ```@CubeIp``` to check the internal IP associated with the container.
2. add two or more test methods which check that the ```@CubeIp``` annotated field must be non-null

I have created a simple test project with the tests that fail here:
https://github.com/rivasdiaz/arquillian-cube-docker-issue-multipleinstancescubeipenricher

##### Additional Information

Test fails with both last 2 releases (Alpha17. Alpha18) as well as the version compiled from master.
The containers run fine.

**Comment by lordofthejars** [comment]
I think there is a major bug on this, I have tried with Alpha19 and what I get is that the cube container object is trying to get started N times, being N the number of test methods to be executed.

**Comment by lordofthejars** [comment]
Hi, I have been investigating a bit and I created next test:

```java
@Cube
    PingPongContainer pingPongContainer;

    @CubeIp(containerName = "pingpong")
    private String pingpongAddr;

    @Test
    public void shouldReturnOkAsPong() throws IOException {
        String pong = ping();
        assertThat(pong, containsString("OK"));
        assertThat(pingPongContainer.getConnectionPort(), is(5000));
    }

    @Test
    public void shouldInjectCubeIp() {
        assertThat(pingpongAddr, notNullValue());
    }
```

First problem I found and it was a bug was that second test that was executed throws an exception because the container were already started. This happens because in JUnit nullifies all fields after each test method execution, so it means that for each test method the enrichers are run, so the first time the `Cube` was started and the second one since it was already started it throws an exception.

I have fixed this by just checking if this container object was already started or not.

Then I wrote a test for @CubeIp thing. And what is happening is an order problem. Enrichers has no order, so if first is executed the enricher of `CubeIp`, since container object has not started  yet, the value is null, because it is impossible to find which is the ip because container does not exists and injects a null.

So maybe we should add a Warning in documentation about this fact.

WDYT?

**Comment by rivasdiaz** [comment]
I was expecting that the containers would be created before each method and destroyed after each method. I see a lot of potential problems in not doing it that way. For example if I'm using a container that runs a DB, and I store data on the container for one test method, then if the container is still the same in the next method, the data will be there and so affect the execution of other test methods, which is something that should not happen. If that is how it works, I think we need to make it very clear in the documentation.

I also remember the particular problems presented by bot @CubeIp and @HostPort enrichers, as they both depend on the cube running. Following how it was implemented before dynamic container creation, I basically skip those enrichers before the container is created, and then implemented builtin support for those enrichers in the container builder, which is something I definitely don't like. I would prefer the enrichers to be able to communicate to the framework that they need the container created and allow them to enrich before and/or after the container is started, so they could keep the enrichment implementation instead of having the logic in both the enricher and the container builder as it is today.

**Comment by lordofthejars** [comment]
Well about enrichers, now we have what we have hehehe, and it works as this, we should see if we can improve somehow, probably a solution would be injecting the cube things in BeforeEnrichment event instead of in Enrichment itself.

About stoping the container we can change it to be test method, it is really easy. The problem I see is a performance problem of starting and stopping container for each test method.

So I think that both options of when to stop it are valid. Maybe we can make it configurable with an annotation? WDYT?

**Comment by rivasdiaz** [comment]
About starting/stopping containers:
I think an annotation, or maybe just an additional parameter in @Cube would be perfect. Actually I see it as something similar to the connectionMode for the cube extension. For example STARTORCONNECTANDLEAVE would imply creating the container once and reusing it every time. Does STARTANDSTOP creates it per test class, per test method, or only at the beginning of the whole testing process? Ideally should be at least START_AND_STOP_AROUND_CLASS and START_AND_STOP_AROUND_METHOD.

We still would need to decide what would be the default scenario. On one side, I would prefer it to start/stop before/after each method, as that is how I would expect it to work. On the other side I'm not entirely familiar how classic arquillian works. If I use a container and a deployer method, is Arquillian framework deploying/undeploying on each test method? or the deployed archive is just deployed before every test method and only undeployed after executing all test methods? If the latter is the case, then I guess cubes should work the same way by default, even if it contradicts JUnit philosophy, as that would be more arquillian-like.

About the enrichers problem:
we would also need a mechanism to re-execute enrichers after container creation, because the container is created as part of the enrichment process, so there is no way to have the container before enriching. I was thinking that maybe creating an additional interface for enrichers to implement, so there is a way to find out what enrichers were interested in being called in this very particular case. Maybe there is a simple solution, but that is too close to Arquillian core inner workings and although I tried to debug it a few times, I still don't feel familiar enough with that code to understand if what I'm proposing is too crazy to implement.

With something like this:

interface CubeTestEnricher extends TestEnricher {
    void enrich(Object testOrContainer, Cube cube);
}

An enricher like CubeIpTestEnricher could ignore the first call (would never do anything without the cube) and then on the second call do its magic.

Another crazy idea: defining some how dependencies among enrichers. That would make CubeIpTestEnricher always run after the enricher that create the container, which would probably solve the problem.

I understand that what we have works, and probably I should focus on the other part. This enhancement is not as important right now. Just something we could think about again in the future.

**Comment by lordofthejars** [comment]
About enrichers I agree with you, let's wait because I am going to ask about ideas in next cabal to see if we can modify Arquilian core to adapt this feature, or just put something specific for Cube.

About second thing, Arquillian has two phases the one that only works if you configure Arquillian in embedded or managed way that is starting and stopping the application server. This operations happens once per test suite (aka test class, this is going to change with jUnit 5 and Arquillian 1.2). Then the second phase is the deployment one which happens once per test class too. So effectively Arquillian works in terms of "classes". For this reason originally we took that starting Docker containers were like starting application server, and should happens once per test suite (aka test class). Also since the first idea was to create Cube for e2e tests, it means that you are not going to define just one container but some of them (one per application server, another for db, ...) so starting and stopping for each test method means a big amount of time.

But then appear it Container Objects and we still the same philosophy but I agree with you that in this case stopping phase should be configurable.

So what I would do is: For `docker-compose` left it as is. For container object, we can offer a new attribute on `@Cube` annotation to set when to start and stop the container object. For me the default mode would be per test class for 2 reasons: the first one because it is safe in terms of performance and we can document it, the second one is that since you define them at class level it seems that lifecycle should be class scope. Of course as you mention you could expect or wanted to have it method scope, in this cases we can do 2 things: 1) provide an attribute as we mention and 2) support the annotation of test methods `public void myTest(@Cube CubeObject cc)` and in this case make it test method scope by default. (I need to investigate this last option).

Currently I am working with Container Objects implementation so before doing any deep change and to avoid merge hell, let me push this new code (https://github.com/arquillian/arquillian-cube/issues/619) and then let's implement what we decide here.

WDYT?

**Comment by rivasdiaz** [comment]
Sounds good to me.

The way things are, the two issues we have been discussing should be additional enhancement requests instead, and agree with you that the default should be that containers will live for the whole time the test class is being executed.

About this particular bug, I just tested my sample test case (the one I mention in the initial report) and it still doesn't work with master, (including your merged code that checks for the container already running).

**Comment by lordofthejars** [comment]
I'll take a look or this evening or tomorrow morning. But I suspect that enricher is executed before CubeRegistry contains the container object registered.

**Comment by rivasdiaz** [comment]
I just added a new test case to my example project. The new test case creates a new container object dynamically using ContainerObjectFactory on each method, and destroy is at the end of each method. The test passes OK with 1.0.0.Alpha19 but fails with current master.

**Comment by lordofthejars** [comment]
I will try it but I suspect that when you stop a container you need to remember to remove it from cube registry. When a container object is created you add the definition in cube registry, so when you remove it you also need to remove from there. If not then (maybe) AfterClassContaierObject is trying to stop a none existing container, but I will need to see if my supposition is ok or not.

**Comment by rivasdiaz** [comment]
In version 1.0.0.Alpha19, at least with container objects created dynamically with ContainerObjectFactory, I can create a container at the beginning of a test method, then stop and destroy it at the end of the method. If I do the same in all my test methods, it works as expected. That means that cube.destroy is probably cleaning up everything. Something in master is breaking that behavior.

**Comment by lordofthejars** [comment]
The problem is that stop and remove operations does not remove instance
from cube registry. So the second execution fails because cube thinks that
container is still up and running.
By design you cannot mix start a container with cube automatic method and
then stopped manually. If you check the factory object you crested you'll
notice that when you are starting you are also registering in cube registry.

Then you call cube controller stop in test but this does not remove from
registry.

**Comment by lordofthejars** [comment]
Look in master branch we have this https://github.com/arquillian/arquillian-cube/blob/master/docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectBuilder.java#L409 so since `stop` and `destroy` are not touching the cube registry, cube still thinks contaienrs are running. As I mention in previous comment, you cannot mix lifecycle managements. Or you start and stop with cube controller or with container objects.
