### ISSUE TITLE
Problem overriding properties in the openshift extension.

### ISSUE THREAD

**Issue by iocanel** [arquillian/arquillian-cube#626]
`CubeOpenshfitConfiguration` is extending `DefaultConfiguration`. The first one is managed by the openshift extension, while the second one is managed by the kubernetes extension.

The problem is that some objects (e.g. `SessionManager`) may get injected with the `DefaultConfiguration` practically ignoring all configuration set by the openshift extension. For example, the snippet bellow has no effect:

        <extension qualifier="openshift">
            <property name="definitionsFile">src/test/resources/hello-openshift.json</property>
        </extension>

I think that @dipak-pawar hit this issue and added a setDestinationFile() method on the configuration object. Still this applies to any property and not just `definitionsFile` and also mutating the configuration is not ideal.

I think that we should not publish both objects and that the `CubeOpenShiftConfigurator` should just ovverride the `ConfigurationRegistar`.

**Comment by lordofthejars** [comment]
Yes overriding objects is something fully supported in Arquillian and we use this approach for example in Drone + Cube integration.

**Comment by dipak-pawar** [comment]
@iocanel , we are injecting `DefaultConfiguration` object first, then we are injecting `OpenshiftConfiguration` object. But in the session manager we are using object of DefaultConfiguration which is weired.

If we are using openshift extension then we should use  OpenshiftConfiguration object inn SessionManager instead of using DefaultConfiguration object each time, then we won't have this problem & there is no need to set openshift specific properties.

**Comment by iocanel** [comment]
@dipak-pawar: exactly!
