### ISSUE TITLE
docker-compose command results in quoted command

### ISSUE THREAD

**Issue by adhesivee** [arquillian/arquillian-cube#676]
I have a docker-compose.yml configuration and the problem that I have is that the action in `command` gets quoted. 
I have the following files:
docker-compose.yml
```
version: '2'
services:
    wildfly-test:
        build: .
        ports:
            - 8080:8080
            - 9990:9990
        command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
```
Dockerfile
```
FROM jboss/wildfly:10.1.0.Final

RUN /opt/jboss/wildfly/bin/add-user.sh test test --silent
```
arquillian.xml
```<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns="http://jboss.org/schema/arquillian"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://jboss.org/schema/arquillian http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

    <container qualifier="wildfly" default="true">
            <property name="chameleonTarget">wildfly:10.1.0.Final:remote</property>
            <property name="username">test</property>
            <property name="password">test</property>
        </configuration>
    </container>
    <extension qualifier="docker">
        <property name="serverUri">tcp://127.0.0.1:2375</property>
        <property name="definitionFormat">COMPOSE</property>
        <property name="dockerContainersFile">docker-compose.yml</property>
        <property name="clean">true</property>
        <property name="cubeSpecificProperties">
          wildfly-test:
            await:
              strategy: http
              responseCode: 200
              url: http://localhost:8080/
              sleepPollingTime: 1s
              iterations: 15
        </property>
    </extension>
</arquillian>
```

When I run this with Cube, then I get error:
`Caused by: com.github.dockerjava.api.exception.NotFoundException: {"message":"oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"\\\": executable file not found in $PATH\"\n"}`

I can reproduce this error when I do the following command in docker: `docker exec <wildfly-container-name>"/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0"`. (exec **with** quotes)

It works when I move the command from docker-compose.yml to Dockerfile.
So it seems that Cube adds quotes around the command which is defined in the docker-compose.yml.

**Comment by lordofthejars** [comment]
Thank you very much for using Arquillian Cube. Currently I am not sure exactly adding quotes explicitly, so I think it is a deeper bug. Look at this class https://github.com/arquillian/arquillian-cube/blob/master/docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ContainerBuilder.java#L388 is where the read string from yaml file is passed into our internal class. Andnotice that we are doing an `Array.asList` call.

Then at https://github.com/arquillian/arquillian-cube/blob/master/docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java#L410 is where the command is executed. If you check what's is happening in this line is that we are doing the final call to `docker-java` library to execute the command, and the problem is the API only supports Array types but you are using the none array form (which is valid from the point of view of docker compose format).

So we would be more than happy if you can help us on solving this problem, if you can do it, can you

1) check that at `DockerClientExecutor` the content of the array is valid (without added extra quotes).

2) provides a PR with a fix, basically the solution should be splitting at `ContainerBuilder` the command by white spaces in case that the string form was used.

We will be more than happy to see a PR from you fixing this, we can help you on that task too, don't hesitate to ask us.

If you cannot, then don't worry, we are going to try to fix as soon as possible, and release a new version with the fix.

Alex.
