### ISSUE TITLE
Binding polling does not correctly set host IP

### ISSUE THREAD

**Issue by tnine** [arquillian/arquillian-cube#81]
When choosing a polling strategy to ensure that startup is successful, it does not correctly discover the IP to ping.  It chooses the docker image IP, NOT the ip of the host where the port will be exposed.  As a result, the ping will never succeeded for users of boot2docker.   I propose the following change.

Make the ping strategy only ping opened ports on the host docker instance ip, not the image ip and it's ports.

**Comment by lordofthejars** [comment]
Hi yes we know this issue, in fact is related with https://github.com/arquillian/arquillian-cube/issues/52

Let me explain the problem on doing in this way, When you do a port binding docker server just opens the port when the container is just started, this doesn't means that the exposed port (the port of server in our case) is available. So when you execute the ping it simply returns saying that the port is ready to serve incoming messages but this is not true because the server (tomcat, wildfly, ...) is not booted up yet, so the ping returns an ok although in reality the server port is not. And this makes that when arquillian tries to deploy the file it returns that the server is not ready to deploy that file. So we decided to use the gateway as a workaround.

Currently we are improving docker-client so when next version will be released we will be able to execute commands inside the docker container, and then we will be able to ping directly inside the container by calling `ss` command. Until then we know that there is a limitation but we cannot do anymore for now. :)

**Comment by tnine** [comment]
@lordofthejars  I've looked at the strategy PollingAwaitStrategy and that makes sense.  I assumed that was the case, we've done a similar style for process forking tomcat, Cassandra and Elastic Search.  I was thinking of performing the following.

In the AwaitStrategyFactory, where we produce the PollingStrategy, modify the PollingStrategy to perform the following.

If the user has defined a http client, then we know this means we're connecting to an API.  This ip could be localhost, or a remote ip, or a virtual machine, it won't matter, it's routable and can be seen by the client, otherwise our client would completely fail.

Currently we use the IP that has been returned from docker as the guest ip, instead use the IP from the client URI configured in the plugin.  I propose we use the client ip/hostname to verify, then only verify the ports that have been marked as portBindings in the yaml.  Clients would only "care" about these ports, since they've mapped to the host system ports.

I've implemented this locally, and it works well.  This approach introduces the requirement that ports your application utilizes about must be mapped via the portBindings.  This would then work for all all possible deployment scenarios.  Local, virtual machine, or remote.

Thoughts?

**Comment by tnine** [comment]
Actually, just reviewed the code in BindingUtil.binding(DockerClientExecutor executor, String cubeId)

It appears this strategy is already used, it's just checking the wrong ip.

**Comment by tnine** [comment]
So in testing this further, I found another case that won't work with the current implementation. It's just a configuration change, but a change that's relevant to all users using either a remote or a virtual machin. Take [this blog post](http://ptmccarthy.github.io/2014/07/24/remote-jmx-with-docker/) for example, which is the issue I'm facing.  I was able to fix this by modifying the arquillian.xml file to include the rmi settings, and forward the port.

**Comment by lordofthejars** [comment]
> The user has defined a http client, 

What's happening with none http ports, and how we can know which ports are http are which aren't?

**Comment by tnine** [comment]
@lordofthejars

Sorry, I may not have been clear.  I'm not saying the ports are http.  What I'm saying is we know definitively this information.

The client url is an HTTL url.  The Client hostname/IP from http url will be used with with portBindings.  This could be localhost, or another machine.

We know these ports should be open on the target hostname/IP from the client's connection URL.  Therefore, when we use Ping to validate the TCP or UDP sockets are listening, we should do so with the hostname/IP given to the client, not the ip returned by the docker api.  This only works in the case where docker is running locally.  If we use the client's hostname/ip, this should work for all network deployment topologies as well as localhost.

Make sense?

**Comment by lordofthejars** [comment]
yes that's true sorry to not understand you is there a way to get the hostname then from container?
