### ISSUE TITLE
properties in arquillian.xml take precedence over system properties

### ISSUE THREAD

**Issue by Ladicek** [arquillian/arquillian-cube#816]
##### Issue Overview

I have `arquillian.xml` looking like this:

```xml
<arquillian>
  <extension qualifier="openshift">
    <property name="namespace.use.current">true</property>
    <property name="env.init.enabled">true</property>
  </extension>
</arquillian>
```

(Ignore the `env.init.enabled` bit, I know it defaults to `true`, I include it just to make it clear that I depend on that behavior.)

I intentionally set `namespace.use.current` to `true` here so that the tests _default_ to running in current namespace. But sometimes, I want Cube to create the temporary `itest-xxxx` namespace and use it, and I'm invoking Maven with `-Dnamespace.use.current=false` to do that.

##### Expected Behaviour

A temporary namespace is created and used.

##### Current Behaviour

Current namespace is used even though I specify `-Dnamespace.use.current=false`.

##### Steps To Reproduce
1. git clone -b arquillian-cube http://github.com/Ladicek/wfswarm-rest-http/
2. cd wfswarm-rest-http
3. mvn clean verify -Popenshift,openshift-it -Dnamespace.use.current=false -DenableImageStreamDetection=true

##### Additional Information

This is caused by the `org.arquillian.cube.impl.util.ConfigUtil` implementation. The first method's javadoc actually says

```
The lookup order is system > env > map > defaultValue.
```

but the implementation doesn't conform to that javadoc.

I can send a PR, it's a pretty simple change, but I want to confirm first that it's really a bug. (I think it is.)

**Comment by lordofthejars** [comment]
Humm I am not sure since surefire also does some strange things when propagating system properties and this features comes from arquillian core, and I am sure it has been widely tested and used, but for just in case try this:

First of all and IIRC maybe @MatousJobanek  can help on this the -D property should `-Dopenshift.namespace.use.current=false` since I think that you need to qualify the system property.

If does not work it is better to try this:

Change `<property name="namespace.use.current">true</property>` to `<property name="namespace.use.current">${useCurrentNamespace:true}</property>` Now notice that what I saying is use `true` if system property `useCurrentNamespace` is not set otherwise use the value.

If still does not work then in your test try to do a sysout of the system property, to check if System Property is correctly bypassed by surefire.

**Comment by lordofthejars** [comment]
but `arquillian.xml` can work as well. But it might be a bug on Cube as you mention that overrides this, would you provide a PR with the fix? For what you mention it seems that you've already modified the code.

**Comment by Ladicek** [comment]
Indeed I changed the code to try if I can fix it in Cube, my changes are here: https://github.com/arquillian/arquillian-cube/pull/818
