### ISSUE TITLE
Use comma to separate multiple values in arquillian.xml

### ISSUE THREAD

**Issue by spisiakm** [arquillian/arquillian-cube#931]
##### Issue Overview

We ran into this issue when using Arquillian Cube to test Vert.x ConfigMap booster on OSO Pro. We're adding additional kubernetes resources through `env.dependencies` property in arquillian.xml. When a path to additional kubernetes/openshift resources contains a whitespace, it gets separated at this place, which results in an error - *FileNotFoundException*. Example: run a booster from a directory that contains a space in the name, for example `/home/Vert.x boosters/....` 

This could be resolved by using comma (and arbitrarily long string of whitespaces after that) to separate multiple values rather than just whitespaces.

##### Expected Behaviour

Additional kubernetes resources are located correctly even if the absolute path to them contains a whitespace.

##### Current Behaviour

If the absolute path contains a whitespace, it is split at this place, which results in an error.

##### Steps To Reproduce
1. `git clone git@github.com:openshiftio-vertx-boosters/vertx-configmap-booster-redhat.git` in any directory that contains a whitespace in the name
2. `mvn clean verify -Popenshift,openshift-it` from this directory. Note that you must be logged to an existing OpenShift instance.

**Comment by lordofthejars** [comment]
Thank you very much.

**Comment by Ladicek** [comment]
Frankly, I don't think this is a proper fix. I can put a comma into a file path and will be screwed again. IMHO, a proper fix would be either adding some form of escaping / quotation, or using XML elements for individual elements. I even think it would be possible to implement both options in a backwards-compatible way.

**Comment by lordofthejars** [comment]
I agree that you can still put a comma in a path, but it is really strange to have a path with commas. Also, having whitespace as separator even escaping them is a good idea from the point of view of the user since checking the attribute you don't clearly know what is a new path and what's not.

Saying that of course, the best solution would be as you mention having XML elements there but then I think that what we are doing is a reparsing of an XML document. Something to discuss if this can be provided by core.
